### ISSUE TITLE
Install Android App raises error

### ISSUE THREAD

**Issue by alexkuc** [expo/xde#131]
When I run "Install Android App", I get the following error message

`
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: host.exp.exponent
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21369)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18443)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21668)
	at android.os.Binder.shellCommand(Binder.java:573)
	at android.os.Binder.onTransact(Binder.java:473)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2642)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3485)
	at android.os.Binder.execTransact(Binder.java:674)
`

My OS is macOS Sierra (10.12.6) and Expo XDE is 2.19.3.

This is output of 'adb devices':
`
List of devices attached
emulator-5554	device
`

**Comment by brentvatne** [comment]
hello!

please follow the issue template when reporting issues

```
We're looking to keep questions on our forums and bug reports on our main Expo repo -- please choose whichever you feel is more appropriate for your issue:

* Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
* File a bug on the Expo repo: https://github.com/expo/expo/issues/new
* Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with XDE!
```
